name: 'Superdataset updater'
description: "Updates TemplateFlow's superdataset when a template has changed"
inputs:
  name:
    description: 'Name that will appear in the commit'
    required: true
    default: 'NiPreps Bot'
  email:
    description: 'Email that will appear in the commit'
    required: true
    default: 'nipreps@gmail.com'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.email }}