name: 'Datalad deploy test'
on:
  workflow_call:
    inputs:
      name:
        description: 'Name that will appear in the commit'
        type: string
        required: true
        default: 'CNeuromod Bot'
      email:
        description: 'Email that will appear in the commit'
        type: string
        required: true
        default: 'courtois.neuromod@gmail.com'
    secrets:
      ssh_key:
        required: true
      git_token:
        required: false
      s3_access_key:
        required: false
      s3_secret_key:
        required: false
jobs:
  deploy_on_linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/courtois-neuromod/dataset-tests:main
      env:
        SECRET_KEY: ${{ secrets.ssh_key }}
        GIT_USERNAME: ${{ inputs.name }}
        GIT_EMAIL: ${{ inputs.email }}
        AWS_ACCESS_KEY_ID: ${{ secrets.s3_access_key }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_secret_key }}
        GIT_TOKEN: ${{ secrets.git_token }}
    steps:
      - name: debug
        run: env
      - name: "setup gh ssh"
        run: |
          mkdir -p /root/.ssh/
          ssh-keyscan -H github.com | install -m 600 /dev/stdin /root/.ssh/known_hosts
      - name: "Test deploy"
        run: |
          pytest --log-cli-level=INFO /actions/tests

  deploy_on_windows:
    runs-on: windows-latest
    needs: deploy_on_linux # only run if tests pass on linux
    env:
      SSH_PRIVATE_KEY: ${{ secrets.ssh_key }}
      GIT_USERNAME: ${{ inputs.name }}
      GIT_EMAIL: ${{ inputs.email }}
      AWS_ACCESS_KEY_ID: ${{ secrets.s3_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_secret_key }}
      GIT_TOKEN: ${{ secrets.git_token }}
    steps:
      - name: setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.11
      - name: setup datalad
        run: |
          python -m pip install datalad-installer
          datalad-installer git-annex -m datalad/git-annex:release
          git config --global filter.annex.process "git-annex filter-process"
          python -m pip install datalad pytest pytest-order ssh_agent_setup
      - name: "Test deploy"
        shell: bash
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H -t rsa ${GITHUB_SERVER_URL##https://} >> $HOME/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          git config --global datalad.ssh.identityfile ~/.ssh/id_rsa
          git clone https://github.com/courtois-neuromod/actions-datasets.git /tmp/actions
          pytest -v --full-trace --log-cli-level=INFO /tmp/actions/tests/deploy
