name: 'Datalad deploy test'
on:
  workflow_call:
    secrets:
      ssh_key:
        required: true
jobs:
  deploy_in_container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/courtois-neuromod/datalad:alpine
      env:
        SECRET_KEY: ${{ secrets.ssh_key }}
        GITHUB_ACTION_REPOSITORY: courtois-neuromod/actions-template
    steps:
      - name: "install tests"
        run: git clone git@github.com/${{ env.GITHUB_ACTION_REPOSITORY }} /actions
      - name: "Test deploy"
        run: pytest /actions/tests
