name: deploy on macOS
on:
  workflow_call:
    inputs:
      name:
        description: 'Name that will appear in the commit'
        type: string
        required: true
        default: 'CNeuromod Bot'
      email:
        description: 'Email that will appear in the commit'
        type: string
        required: true
        default: 'courtois.neuromod@gmail.com'
    secrets:
      ssh_key:
        required: true
jobs:
  deploy:
    runs-on: macos-latest
    env:
      SECRET_KEY: ${{ secrets.ssh_key }}
      GITHUB_ACTION_REPOSITORY: courtois-neuromod/actions-template
      GIT_USERNAME: ${{ inputs.name }}
      GIT_EMAIL: ${{ inputs.email }}
    steps:
      - name: Install datalad
        run: |
          brew update
          brew install datalad
          pip install pytest ssh_agent_setup
      - name: Checkout actions repo
        uses: actions/checkout@v3
        with:
          repository: courtois-neuromod/actions-template
          path: ./actions
      - name: "Test deploy"
        run: pytest actions/tests
