name: deploy on macOS
on:
  workflow_call:
    inputs:
      name:
        description: 'Name that will appear in the commit'
        type: string
        required: true
        default: 'CNeuromod Bot'
      email:
        description: 'Email that will appear in the commit'
        type: string
        required: true
        default: 'courtois.neuromod@gmail.com'
    secrets:
      ssh_key:
        required: true
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Install datalad
        run: |
          brew update
          brew install datalad
      - name: Test intalling the dataset
        shell: bash
        env:
          SSH_KEY: ${{ secrets.ssh_key }}
        run: |
          git config --global user.name ${{ inputs.name }}
          git config --global user.email ${{ inputs.email }}
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh
          # Add github as trusted hosts
          ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts
          chmod 600 $HOME/.ssh/known_hosts
          # Start ssh agent
          eval "$(ssh-agent -s)"
          # add bot ssh key
          ssh-add - <<< "$SSH_KEY"
          # test install
          datalad install -r git@github.com:courtois-neuromod/${GITHUB_REPOSITORY##*/}.git
          cd ${GITHUB_REPOSITORY##*/}
          # check available remotes
          git remote -v
